name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_zad1
      id: test_zad1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_zad1
        setup-command: ''
        command: python -m unittest test_zad1.py
        timeout: 10
        max-score: 10
    - name: test_zad2
      id: test_zad2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_zad2
        setup-command: ''
        command: python -m unittest test_zad2.py
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ZAD1_RESULTS: "${{steps.test_zad1.outputs.result}}"
        TEST_ZAD2_RESULTS: "${{steps.test_zad2.outputs.result}}"
      with:
        runners: test_zad1,test_zad2
